name: CI

on:
  push:
    branches:
      - master
      - 0-8-stable
  pull_request:
    branches:
      - master
      - 0-8-stable

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    name: ${{ matrix.feature }} ruby-${{ matrix.ruby }} ${{ matrix.orm.name }}-${{ matrix.orm.version}} ${{ matrix.database }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '2.6'
          - '2.5'
          - '2.4'
        database:
          - 'sqlite3'
          - 'mysql'
          - 'postgres'
        orm:
          - name: 'active_record'
            version: '4.2'
          - name: 'active_record'
            version: '5.0'
          - name: 'active_record'
            version: '5.1'
          - name: 'active_record'
            version: '5.2'
          - name: 'active_record'
            version: '6.0'
          - name: 'sequel'
            version: '4'
          - name: 'sequel'
            version: '5'
        experimental: [false]
        feature: ['unit']
        include:
          - ruby: '2.6'
            database: 'sqlite3'
            feature: 'performance'
            experimental: false
          - ruby: '2.6'
            database: 'sqlite3'
            feature: 'i18n_fallbacks'
            experimental: false
          - ruby: '2.6'
            database: 'sqlite3'
            feature: 'unit'
            orm:
              name: 'active_record'
              version: '6.1'
            experimental: true
          - ruby: '2.6'
            database: 'mysql'
            feature: 'unit'
            orm:
              name: 'active_record'
              version: '6.1'
            experimental: true
          - ruby: '2.6'
            database: 'postgres'
            feature: 'unit'
            orm:
              name: 'active_record'
              version: '6.1'
            experimental: true
        exclude:
          - ruby: '2.4'
            orm:
              name: 'active_record'
              version: '6.0'
    env:
      DB: ${{ matrix.database }}
      BUNDLE_JOBS: 4
      BUNDLE_PATH: vendor/bundle
      ORM: ${{ matrix.orm.name }}
      ORM_VERSION: ${{ matrix.orm.version }}
      MYSQL_PASSWORD: root
      PGHOST: localhost
      PGPORT: 5432
      PGUSER: postgres
      RAILS_ENV: test
      FEATURE: ${{ matrix.feature }}

    services:
      postgres:
        image: postgres:11.5
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      mysql:
        image: mysql:5.7
        ports: ["3306:3306"]
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          MYSQL_ROOT_PASSWORD: root

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update packages
        run: sudo apt-get update
      - name: Install Sqlite
        run: sudo apt-get install libsqlite3-dev -y
        if: matrix.database == 'sqlite3'
      - name: Install Postgres
        run: sudo apt-get install libpq-dev postgresql-client -y
        if: matrix.database == 'postgres'
      - name: Install MySQL
        run: sudo apt-get install libmysqlclient-dev mysql-client -y
        if: matrix.database == 'mysql'
      - id: cache-bundler
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ matrix.ruby }}-${{ matrix.orm.name }}-${{ matrix.orm.version }}-${{ matrix.feature }}-${{ hashFiles('mobility.gemspec') }}-${{ hashFiles('Gemfile') }}
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install latest Bundler
        run: gem install bundler --no-document
      - name: Install dependencies
        run: bundle install
      - name: Setup test db
        run: bundle exec rake db:create db:up
      - name: Run tests
        run: bundle exec rake
